import type { TranslationPayload } from './translation-types';

// The initial English copy keeps the public site useful on its first deploy.
// Administrators can replace these drafts in the translation dashboard later.
const phrases: ReadonlyArray<readonly [string, string]> = [
  ['從天然或加工的食品原物料依顏色/外觀\n瑕疵透過自動化分選機完成品質等級分類', 'Automated sorting classifies natural or processed food ingredients by colour and appearance defects.'],
  ['各類食品包裝型態的X光機檢查,為食品出廠前的安全把關', 'X-ray inspection for every food packaging format helps safeguard products before shipment.'],
  ['肉類及無刺鮮魚的高解析度X光機', 'High-resolution X-ray systems for meat and boneless fresh fish.'],
  ['食品容器生產的物理性發泡技術裝置', 'Physical foaming equipment for food-container production.'],
  ['消費端廢棄物整體風選分類設備', 'Complete air-separation and sorting equipment for post-consumer waste.'],
  ['填寫下列表單後，系統會直接將需求送交合軒科技；業務團隊將於一個工作天內回覆。', 'Complete the form to send your requirements directly to Unirise Technology. Our sales team will reply within one business day.'],
  ['請說明您的產線需求、欲檢測／分選的產品與預計導入時間。', 'Please describe your production-line requirements, the products to inspect or sort, and your expected implementation timeline.'],
  ['已收到您的詢問；我們將於一個工作天內以電子郵件與您聯絡。', 'We received your enquiry and will contact you by email within one business day.'],
  ['已收到您的詢問；通知服務暫時延遲，我們仍會儘快與您聯絡。', 'We received your enquiry. Notifications are temporarily delayed, but we will contact you as soon as possible.'],
  ['目前無法送出詢問，請稍後再試，或直接聯絡我們。', 'We cannot send your enquiry right now. Please try again later or contact us directly.'],
  ['「{group}」為合軒科技原網站所列的正式產品與服務分類。', '“{group}” is an official product and service category listed on the Unirise website.'],
  ['完整規格、選配與適用產線請向合軒科技確認。', 'Please contact Unirise Technology to confirm full specifications, options, and suitable production lines.'],
  ['您好，我是合軒科技的測試版網站助理。我可以協助您了解產品領域、代理品牌、聯絡方式與詢價流程。', 'Hello, I am the Unirise website assistant. I can help you explore product areas, represented brands, contact details, and the enquiry process.'],
  ['目前詢問較多，請稍後一分鐘再試。', 'We are receiving many questions. Please try again in one minute.'],
  ['測試版聊天服務正在設定中，請稍後再試或直接聯絡合軒科技。', 'The chat service is still being configured. Please try again later or contact Unirise directly.'],
  ['目前無法取得回覆，請稍後再試或直接使用詢價系統。', 'We cannot retrieve a reply at the moment. Please try again later or use the enquiry form.'],
  ['聊天內容請勿輸入敏感個資。', 'Please do not enter sensitive personal information in the chat.'],
  ['聯絡資料僅用於回覆本次需求。', 'Your contact details are used only to respond to this request.'],
  ['已收到您的需求；目前通知服務暫時無法使用，聯絡可能稍有延遲。', 'We received your request. Notifications are temporarily unavailable, so our reply may be delayed.'],
  ['已收到您的需求，我們會儘快與您聯絡。', 'We received your request and will contact you as soon as possible.'],
  ['資料未能送出，請確認必填欄位後再試。', 'Your information could not be sent. Please check the required fields and try again.'],
  ['送出次數較多，請稍後再試。', 'Too many submissions. Please try again later.'],
  ['雞骨魚骨專用X光異物檢測機 Xavis', 'Xavis X-ray Foreign-Object Inspection System for Fish and Chicken Bones'],
  ['M1 SF 皮帶稱重機和袋裝填充機 Manter', 'Manter M1 SF Belt Weigher and Bag Filling Machine'],
  ['多段式重量分級機 Xavis', 'Xavis Multi-stage Weight Grader'],
  ['番茄自動包裝線 Manter', 'Manter Automated Tomato Packaging Line'],
  ['厚薄測量儀 SBI', 'SBI Thickness Measurement System'],
  ['【精準掌握厚度變化，讓押出製程更穩定】', 'Precise thickness control for a more stable extrusion process.'],
  ['合軒科技｜厚薄測量儀 SBI 在塑膠薄膜、片材等連續押出製程中，厚度均勻性直接影響產品品質與材料成本。', 'The Unirise SBI thickness measurement system helps film and sheet extrusion lines control thickness uniformity, product quality, and material cost.'],
  ['SBI 厚薄測量儀採用非接觸式高精度測量技術，即時掌握產品厚度變化與整幅厚度分布，協助生產線快速發現異常、調整製程，讓品質控制更即時、更精準。', 'Non-contact, high-precision measurement monitors thickness changes and the full web profile in real time, helping operators identify deviations and adjust the process quickly.'],
  ['✅高精度 × 非接觸式測量', 'High precision and non-contact measurement.'],
  ['不接觸產品即可精準測量，降低刮傷、變形及污染風險。', 'Measures accurately without touching the product, reducing the risk of scratches, deformation, and contamination.'],
  ['✅即時監控厚度變化', 'Real-time thickness monitoring.'],
  ['持續掌握生產狀態，及早發現過厚、過薄等異常並進行調整。', 'Continuously monitors production so over-thickness and under-thickness conditions can be corrected early.'],
  ['✅厚度均勻性分析', 'Thickness uniformity analysis.'],
  ['分析產品整幅厚度分布，協助改善局部厚薄不均問題。', 'Analyses the full-width thickness profile to help correct local variation.'],
  ['✅降低原料浪費', 'Reduced material waste.'],
  ['精準控制材料用量，在維持產品品質的同時，有效降低生產成本。', 'Controls material use precisely to reduce production cost while maintaining product quality.'],
  ['✅智慧製程控制', 'Intelligent process control.'],
  ['測量數據可導入製程管理，並與押出設備及自動控制系統整合，提升產線自動化與穩定性。', 'Measurement data can feed process management and integrate with extrusion and automation systems to improve line stability.'],
  ['適用於塑膠薄膜、片材及各類連續押出製程，從即時測量到製程控制，協助企業提升產品一致性與生產效率。', 'Suitable for film, sheet, and other continuous extrusion processes, from real-time measurement through closed-loop process control.'],
  ['專為魚刺、魚骨及雞骨等低密度異物設計的 X 光檢測系統。結合高解析 X 光成像與 AI 辨識技術，提升檢測精度與食品安全。', 'An X-ray inspection system designed for low-density foreign objects such as fish bones and chicken bones. High-resolution imaging and AI recognition improve detection accuracy and food safety.'],
  ['專為易受損蔬果打造的自動化包裝系統。結合溫和秤重與自動袋裝填充，兼顧產品品質與包裝效率。', 'An automated packaging system for delicate fruit and vegetables, combining gentle weighing and automatic bag filling to protect product quality and packaging efficiency.'],
  ['專為提升水產加工效率而設計的自動化分級設備。兼顧分級精度、作業效率與產品規格一致性。', 'Automated grading equipment designed to improve seafood-processing efficiency while maintaining grading accuracy, operating efficiency, and consistent product specifications.'],
  ['專為番茄及易受損蔬果打造的自動化包裝系統。兼顧產品品質、包裝效率與產線彈性配置需求。', 'An automated packaging system for tomatoes and delicate fruit and vegetables, balancing product quality, packaging efficiency, and flexible production-line configuration.'],
  ['有哪些食品分選方案？', 'What food-sorting solutions are available?'],
  ['X 光檢測能協助什麼？', 'How can X-ray inspection help?'],
  ['如何聯絡或詢價？', 'How can I contact Unirise or request a quote?'],
  ['食品生產者到消費端的循環自動化方案', 'Circular automation solutions from food production to post-consumer recovery'],
  ['食品生產循環自動化方案', 'Food-production circular automation solutions'],
  ['食材分選', 'Food Sorting'],
  ['X光機異物檢測', 'X-ray Foreign-Object Inspection'],
  ['回收再生', 'Recycling and Recovery'],
  ['塑膠化工', 'Plastics and Chemicals'],
  ['產業服務', 'Industry Services'],
  ['代理品牌', 'Represented Brands'],
  ['最新消息', 'News'],
  ['下載專區', 'Downloads'],
  ['詢價系統', 'Request a Quote'],
  ['聯絡我們', 'Contact Us'],
  ['產品目錄', 'Product Catalog'],
  ['解決方案總覽', 'Solution Overview'],
  ['上一張主視覺', 'Previous slide'],
  ['下一張主視覺', 'Next slide'],
  ['首頁', 'Home'],
  ['選擇語言⌄', 'Select Language⌄'],
  ['聯絡', 'Contact'],
  ['詢價', 'Inquiry'],
  ['產品詢問與資料索取', 'Product Enquiries and Information Requests'],
  ['加入詢問車', 'Add to Enquiry'],
  ['公司地址', 'Address'],
  ['詢問車', 'Enquiry List'],
  ['語系', 'Language'],
  ['回到首頁', 'Back to Home'],
  ['主要選單', 'Main Navigation'],
  ['開啟選單', 'Open Menu'],
  ['回到頂端', 'Back to Top'],
  ['展開產業服務子選單', 'Expand industry-services submenu'],
  ['展開代理品牌子選單', 'Expand represented-brands submenu'],
  ['展開下載專區子選單', 'Expand downloads submenu'],
  ['台南市東區裕義路598號', 'No. 598, Yuyi Road, East District, Tainan City, Taiwan'],
  ['合軒科技有限公司', 'Unirise Technology Inc.'],
  ['合軒科技網站助理', 'Unirise Technology Website Assistant'],
  ['我們提供', 'We provide'],
  ['品牌介紹', 'Brand Overview'],
  ['自動重量檢測機', 'Automatic Checkweighers'],
  ['重量分級檢測機', 'Weight Grading Systems'],
  ['食品異物X光機檢測', 'Food X-ray Foreign-Object Inspection'],
  ['鋁箔金屬檢測機', 'Metal Detection for Foil Packaging'],
  ['工業產品X光機檢測', 'Industrial-product X-ray Inspection'],
  ['採樣分析', 'Sampling Analysis'],
  ['板材押出生產線', 'Sheet Extrusion Lines'],
  ['物理發泡', 'Physical Foaming'],
  ['測厚儀', 'Thickness Gauges'],
  ['手持式分析儀', 'Handheld Analysers'],
  ['破袋機', 'Bag Openers'],
  ['渦電流分選機', 'Eddy-current Separators'],
  ['磁滾筒', 'Magnetic Drums'],
  ['上吸式磁鐵', 'Overband Magnets'],
  ['鋁罐分選機', 'Aluminium-can Sorters'],
  ['聯絡方式與詢價流程', 'contact details and the enquiry process'],
  ['公司名稱', 'Company'],
  ['公司', 'Company'],
  ['姓名', 'Name'],
  ['公司：', 'Company:'],
  ['電話', 'Phone'],
  ['信箱', 'Email'],
  ['地址', 'Address'],
  ['立即聯絡', 'Contact us now'],
  ['聯絡電話', 'Phone'],
  ['電子信箱', 'Email'],
  ['詢問產品', 'Product of Interest'],
  ['需求說明', 'Requirements'],
  ['送出詢問', 'Send Enquiry'],
  ['送出中…', 'Sending…'],
  ['服務電話', 'Service Phone'],
  ['產品資料索取', 'Request Product Information'],
  ['請填寫此欄位。', 'Please complete this field.'],
  ['請輸入有效的電子郵件地址。', 'Please enter a valid email address.'],
  ['聯絡專員', 'Talk to a Specialist'],
  ['索取報價', 'Request a Quote'],
  ['開啟聊天', 'Open Chat'],
  ['關閉聊天', 'Close Chat'],
  ['送出問題', 'Send Question'],
  ['請輸入您的問題', 'Enter your question'],
  ['正在回覆', 'Replying'],
  ['參考網站內容：', 'Website sources:'],
  ['累計訪客', 'Total visitors'],
  ['今日訪客', 'Visitors today'],
  ['訪客統計載入中', 'Loading visitor statistics'],
  ['上一組品牌', 'Previous brands'],
  ['下一組品牌', 'Next brands'],
  ['主視覺輪播', 'Main visual carousel'],
  ['向下捲動', 'Scroll down'],
  ['了解更多', 'Learn more'],
  // Navigation and catalogue labels. These are shown in the desktop and mobile
  // menus, so a partial translation here makes a correctly routed English page
  // still look bilingual.
  ['X光檢測', 'X-ray Inspection'],
  ['風選機', 'Air Separation'],
  ['X光食品異物檢測', 'Food X-ray Foreign-Object Inspection'],
  ['渦電流及除鐵設備', 'Eddy-current and Magnetic Separation Equipment'],
  ['OPTIMUM-食材分選', 'OPTIMUM-Food Sorting'],
  ['Smart Grader-採樣分析', 'Smart Grader-Sampling Analysis'],
  ['XAVIS-X光機檢測', 'XAVIS-X-ray Inspection'],
  ['XAVIS-FSCAN自動重量檢測機', 'XAVIS-FSCAN Automatic Checkweighers'],
  ['XAVIS-FSCAN重量分級檢測機', 'XAVIS-FSCAN Weight Grading Systems'],
  ['XAVIS-FSCAN鋁箔金屬檢測機', 'XAVIS-FSCAN Metal Detection for Foil Packaging'],
  ['NIR手持式分析儀', 'NIR Handheld Analysers'],
  ['NIHOT-回收再生', 'NIHOT-Recycling and Recovery'],
  ['Matthiessen-破袋機', 'Matthiessen-Bag Openers'],
  ['MEAF-板材押出生產線', 'MEAF-Sheet Extrusion Lines'],
  ['PROMIX-物理發泡', 'PROMIX-Physical Foaming'],
  ['SBI-測厚儀', 'SBI-Thickness Gauges'],
  ['NOVUS (皮帶式-適用新鮮、乾燥或冷凍產品)', 'NOVUS (belt type for fresh, dried, or frozen products)'],
  ['VENTUS (適用堅果和乾果等產品)', 'VENTUS (for nuts and dried fruit)'],
  ['TRIPLUS (自由落體式-適用新鮮、乾燥或冷凍產品)', 'TRIPLUS (free-fall type for fresh, dried, or frozen products)'],
  ['MAGNUS (適用易碎水果)', 'MAGNUS (for delicate fruit)'],
  ['XAVIS-自動重量檢測機', 'XAVIS-Automatic Checkweighers'],
  ['CWF590W輕量型重量檢測機', 'CWF590W Lightweight Checkweigher'],
  ['CWF590WR滾輪式重量檢測機', 'CWF590WR Roller Checkweigher'],
  ['CSCAN自動重量檢測機', 'CSCAN Automatic Checkweigher'],
  ['CWIN69X多列式重量檢測機', 'CWIN69X Multi-lane Checkweigher'],
  ['XAVIS-重量分級檢測機', 'XAVIS-Weight Grading Systems'],
  ['XAVIS重量分級檢測機', 'XAVIS Weight Grading System'],
  ['XAVIS-食品異物X光機檢測', 'XAVIS-Food X-ray Foreign-Object Inspection'],
  ['小包裝/未包裝X光食品自動異物檢測機', 'X-ray Food Foreign-Object Inspection for Small or Unpackaged Products'],
  ['低密度中型包裝/散裝 X光食品自動異物檢測機', 'X-ray Food Foreign-Object Inspection for Low-density Medium Packs or Bulk Products'],
  ['高密度中型包裝 X光食品自動異物檢測機', 'X-ray Food Foreign-Object Inspection for High-density Medium Packs'],
  ['管道式 X光食品自動異物檢測機', 'Pipeline X-ray Food Foreign-Object Inspection System'],
  ['大型包裝 X光食品自動異物檢測機', 'X-ray Food Foreign-Object Inspection for Large Packs'],
  ['小型罐頭/瓶子包裝 X光食品自動異物檢測機', 'X-ray Food Foreign-Object Inspection for Small Cans or Bottles'],
  ['大型罐頭/瓶子包裝 X光食品自動異物檢測機', 'X-ray Food Foreign-Object Inspection for Large Cans or Bottles'],
  ['魚骨/雞骨專用 X光食品自動異物檢測機', 'X-ray Food Foreign-Object Inspection for Fish and Chicken Bones'],
  ['XAVIS-鋁箔金屬檢測機', 'XAVIS-Metal Detection for Foil Packaging'],
  ['MDN-200AD鋁箔金屬檢測機(標準)', 'MDN-200AD Metal Detection for Foil Packaging (Standard)'],
  ['MDN-200AH鋁箔金屬檢測機(進階)', 'MDN-200AH Metal Detection for Foil Packaging (Advanced)'],
  ['XAVIS-工業產品X光機檢測', 'XAVIS-Industrial-product X-ray Inspection'],
  ['電池檢測專用', 'Battery Inspection'],
  ['智慧採樣分析器', 'Smart Sampling Analyser'],
  ['智慧分級機', 'Smart Grader'],
  ['板材押出生產線', 'Sheet Extrusion Line'],
  ['P1 冷卻混合器', 'P1 Cooling Mixer'],
  ['熔體混合器', 'Melt Mixer'],
  ['KAPA I & KAPA II 電容/渦流雙感測厚薄儀', 'KAPA I & KAPA II Capacitive/Eddy-current Dual-sensor Thickness Gauge'],
  ['KAPA IR 紅外線厚薄儀', 'KAPA IR Infrared Thickness Gauge'],
  ['XRS SOFT X-RAY 低能量X光厚薄儀', 'XRS SOFT X-RAY Low-energy X-ray Thickness Gauge'],
  ['SHADOW 雷射陰影測量厚薄儀', 'SHADOW Laser-shadow Thickness Gauge'],
  ['STG 雷射位移測量厚薄儀', 'STG Laser-displacement Thickness Gauge'],
  ['手持式NIR分析儀-塑料用', 'Handheld NIR Analyser for Plastics'],
  ['手持式NIR分析儀-紡織用', 'Handheld NIR Analyser for Textiles'],
  ['手持螢幕NIR分析儀-塑料用', 'Handheld-screen NIR Analyser for Plastics'],
  ['SDM 移動式風選機', 'SDM Mobile Air Separator'],
  ['SDI 風選機', 'SDI Air Separator'],
  ['WSF 風選機', 'WSF Air Separator'],
  ['DDS 風選機', 'DDS Air Separator'],
  ['SDX 風選機', 'SDX Air Separator'],
  ['碟篩', 'Disc Screen'],
  ['SFIIIK3 破袋機', 'SFIIIK3 Bag Opener'],
  ['渦電流分選機', 'Eddy-current Separator'],
  ['磁滾筒', 'Magnetic Drum'],
  ['上吸式磁鐵', 'Overband Magnet'],
  ['鋁罐分選機', 'Aluminium-can Sorter'],
  ['食品生產循環自動化方案', 'Food-production circular automation solutions'],
  ['主視覺輪播', 'Main visual carousel'],
  ['上一組品牌', 'Previous brands'],
  ['下一組品牌', 'Next brands'],
  ['品牌介紹', 'Brand Overview'],
  ['食材分選', 'Food Sorting'],
  ['回收再生', 'Recycling and Recovery'],
  ['塑膠化工', 'Plastics and Chemicals'],
  ['採樣分析', 'Sampling Analysis'],
  ['自動重量檢測機', 'Automatic Checkweighers'],
  ['重量分級檢測機', 'Weight Grading Systems'],
  ['食品異物X光機檢測', 'Food X-ray Foreign-Object Inspection'],
  ['鋁箔金屬檢測機', 'Metal Detection for Foil Packaging'],
  ['工業產品X光機檢測', 'Industrial-product X-ray Inspection'],
  ['物理發泡', 'Physical Foaming'],
  ['測厚儀', 'Thickness Gauges'],
  ['手持式分析儀', 'Handheld Analysers'],
  ['破袋機', 'Bag Openers'],
  ['合軒科技有限公司', 'Unirise Technology Inc.'],
  ['合軒科技', 'Unirise Technology'],
  ['合軒', 'Unirise'],
  ['公司地址', 'Address'],
  ['搜尋', 'Search'],
  ['詢問車', 'Enquiry List'],
  ['語系', 'Language'],
  ['回到首頁', 'Back to Home'],
  ['主要選單', 'Main Navigation'],
  ['開啟選單', 'Open Menu'],
  ['回到頂端', 'Back to Top'],
  ['展開產業服務子選單', 'Expand industry-services submenu'],
  ['展開代理品牌子選單', 'Expand represented-brands submenu'],
  ['展開下載專區子選單', 'Expand downloads submenu'],
  ['台南市東區裕義路598號', 'No. 598, Yuyi Road, East District, Tainan City, Taiwan'],
  ['著作權所有 © 2021 合軒科技有限公司', 'Copyright © 2021 Unirise Technology Inc.'],
  ['訪客統計載入中', 'Loading visitor statistics'],
  ['累計訪客', 'Total visitors'],
  ['今日訪客', 'Visitors today'],
  ['測試版｜公開資訊問答', 'Test version | Public information Q&A'],
  ['索取報價', 'Request a Quote'],
  ['聯絡專員', 'Talk to a Specialist'],
  ['後續服務', 'Next steps'],
  ['索取報價表單', 'Request-a-quote form'],
  ['聯絡專員表單', 'Specialist-contact form'],
  ['關閉聯絡表單', 'Close contact form'],
  ['產品／主題', 'Product / topic'],
  ['聯絡資料僅用於回覆本次需求。', 'Your contact details are used only to reply to this request.'],
  ['送出需求', 'Send request'],
  ['資料未能送出，請確認必填欄位後再試。', 'Your information could not be sent. Please check the required fields and try again.'],
  ['資料未能送出，請稍後再試。', 'Your information could not be sent. Please try again later.'],
  ['已收到您的需求；目前通知服務暫時無法使用，聯絡可能稍有延遲。', 'We received your request. Notifications are temporarily unavailable, so our reply may be delayed.'],
  ['已收到您的需求，我們會儘快與您聯絡。', 'We received your request and will contact you as soon as possible.'],
  ['請輸入您的問題', 'Enter your question'],
  ['聊天問題', 'Chat question'],
  ['送出問題', 'Send question'],
  ['參考網站內容：', 'Website sources:'],
  ['正在回覆', 'Replying'],
  // Catalogue descriptions and product-news copy are visible outside the
  // menus, including on deep links and in the English chatbot knowledge base.
  ['原網站將天然或加工食品原物料依顏色與外觀瑕疵進行自動化品質分級。', 'The original website describes automated quality grading of natural or processed food ingredients by colour and appearance defects.'],
  ['原網站提供各類食品包裝型態的 X 光檢查，作為食品出廠前的安全把關。', 'The original website provides X-ray inspection for a range of food packaging formats to safeguard products before shipment.'],
  ['原網站列出消費端廢棄物的整體風選分類設備與回收再生解決方案。', 'The original website lists complete air-separation equipment and recycling solutions for post-consumer waste.'],
  ['原網站涵蓋食品容器物理性發泡、板材押出與厚薄量測相關技術。', 'The original website covers physical foaming for food containers, sheet extrusion, and thickness-measurement technology.'],
  ['OPTIMUM 食材分選系列包含皮帶式、自由落體式及適用堅果、乾果與易碎水果的機型。', 'The OPTIMUM Food Sorting range includes belt and free-fall models for nuts, dried fruit, and delicate fruit.'],
  ['XAVIS 食品 X 光檢測系列包含未包裝、袋裝、罐裝、瓶裝、管道式與魚骨／雞骨等應用。', 'The XAVIS Food X-ray range covers unpackaged, bagged, canned, bottled, pipeline, fish-bone, and chicken-bone applications.'],
  ['NIHOT 系列包含移動式與固定式風選機、碟篩等回收再生設備。', 'The NIHOT range includes mobile and fixed air separators, disc screens, and other recycling equipment.'],
  ['3. 魚骨/雞骨檢測 FSCAN-4350G X光食品自動異物檢測機', '3. Fish and Chicken Bone Inspection FSCAN-4350G X-ray Food Foreign-Object Inspection System'],
  ['雞骨魚骨專用X光異物檢測機 Xavis', 'Xavis X-ray Foreign-Object Inspection System for Fish and Chicken Bones'],
  ['專為魚刺、魚骨及雞骨等低密度異物設計的 X 光檢測系統。結合高解析 X 光成像與 AI 辨識技術，提升檢測精度與食品安全。', 'An X-ray inspection system for low-density foreign objects such as fish and chicken bones. High-resolution X-ray imaging and AI recognition improve inspection accuracy and food safety.'],
  ['可偵測魚刺、魚骨、雞骨等低密度異物，適用雞胸肉、雞腿肉、魚排、魚片、鮭魚與鱈魚。', 'Detects low-density foreign objects such as fish and chicken bones in chicken breast, chicken legs, fish steaks, fillets, salmon, and cod.'],
  ['高解析度感測器與 FSCAN AI 深度學習演算法，協助提高細小骨刺辨識率、降低漏檢與誤判。', 'High-resolution sensors and the FSCAN AI deep-learning algorithm improve fine-bone recognition while reducing missed detections and false positives.'],
  ['IP69K 食品級衛生設計，可支援生鮮、冷藏、冷凍及熟食產品，並保存檢測影像與批次資料。', 'The IP69K hygienic food-grade design supports fresh, chilled, frozen, and cooked products and retains inspection images and batch data.'],
  ['M1 SF 皮帶稱重機和袋裝填充機 Manter', 'Manter M1 SF Belt Weigher and Bag Filling Machine'],
  ['專為易受損蔬果打造的自動化包裝系統。結合溫和秤重與自動袋裝填充，兼顧產品品質與包裝效率。', 'An automated packaging system for delicate fruit and vegetables, combining gentle weighing and automatic bag filling to protect product quality and packaging efficiency.'],
  ['皮帶式秤重減少產品落差，適用蘋果、梨子、柑橘、洋蔥與馬鈴薯等易碰傷產品。', 'Belt weighing reduces product drops and is suitable for easily bruised products such as apples, pears, citrus, onions, and potatoes.'],
  ['精準控制每袋重量，降低超重填充與原料浪費，維持包裝的一致性。', 'Precisely controls the weight of each bag to reduce overfilling and material waste while keeping packaging consistent.'],
  ['可串接供料、分級、光學選別、封口、裝箱及棧板系統，形成完整自動化包裝產線。', 'Can integrate feeding, grading, optical sorting, sealing, case packing, and pallet systems into a complete automated packaging line.'],
  ['多段式重量分級機 Xavis', 'Xavis Multi-stage Weight Grader'],
  ['專為提升水產加工效率而設計的自動化分級設備。兼顧分級精度、作業效率與產品規格一致性。', 'Automated grading equipment designed to improve seafood-processing efficiency while maintaining grading accuracy, operating efficiency, and consistent product specifications.'],
  ['產品置於托盤後即可自動秤重並依設定重量分級出料，降低人工分選時間。', 'Products are automatically weighed on trays and discharged by the configured weight grades, reducing manual sorting time.'],
  ['可設定 3～7 個分級等級，最小可達 10 克級距，並以電子秤重系統與防水型電磁閥提升準確度。', 'Supports 3 to 7 grading levels in increments as small as 10 grams, using an electronic weighing system and waterproof solenoid valves for improved accuracy.'],
  ['快速拆裝射出成型托盤，配合下噴淋噴嘴與清潔刷，適合鮮魚、水產品與漁獲加工品。', 'Quick-release injection-moulded trays, lower spray nozzles, and cleaning brushes suit fresh fish, seafood, and processed catch products.'],
  ['番茄自動包裝線 Manter', 'Manter Automated Tomato Packaging Line'],
  ['專為番茄及易受損蔬果打造的自動化包裝系統。兼顧產品品質、包裝效率與產線彈性配置需求。', 'An automated packaging system for tomatoes and delicate fruit and vegetables, balancing product quality, packaging efficiency, and flexible production-line configuration.'],
  ['採用多頭組合秤進行高精度自動計量，減少產品損耗與重量誤差。', 'Uses a multihead combination weigher for high-precision automatic weighing, reducing product loss and weight variation.'],
  ['溫和輸送設計可降低碰撞、壓傷與果實破損，維持番茄與蔬果的新鮮外觀。', 'Gentle conveying reduces impact, bruising, and fruit damage to maintain the fresh appearance of tomatoes and produce.'],
  ['可支援網袋、PE 袋、立袋、透明盒與紙箱包裝，並整合自動棧板堆疊。', 'Supports mesh bags, PE bags, stand-up pouches, clear trays, and cartons, with integrated automated palletising.'],
  ['公司服務領域', 'Company service areas'],
  ['合軒科技的公開服務領域為食品分選、X 光檢測、回收再生與塑膠化工。天然或加工食品原物料可依顏色或外觀瑕疵由自動化分選機完成品質等級分類。各類食品包裝型態可透過 X 光檢查，作為食品出廠前的安全把關。', 'Unirise Technology publicly provides food sorting, X-ray inspection, recycling and recovery, and plastics and chemicals solutions. Automated sorters classify natural or processed food ingredients by colour and appearance defects. X-ray inspection across food packaging formats safeguards products before shipment.'],
  ['合軒科技網站列出的代理品牌為：OPTIMUM、XAVIS、Smart Grader、MEAF、PROMIX、SBI、NIR、NIHOT、Matthiessen、合軒。', 'The represented brands listed on the Unirise Technology website are OPTIMUM, XAVIS, Smart Grader, MEAF, PROMIX, SBI, NIR, NIHOT, Matthiessen, and Unirise.'],
  ['OPTIMUM 食材分選', 'OPTIMUM Food Sorting'],
  ['OPTIMUM 食材分選系列包括 NOVUS 皮帶式機型（適用新鮮、乾燥或冷凍產品）、VENTUS（適用堅果和乾果）、TRIPLUS 自由落體式機型（適用新鮮、乾燥或冷凍產品）及 MAGNUS（適用易碎水果）。', 'The OPTIMUM Food Sorting range includes NOVUS belt models for fresh, dried, or frozen products; VENTUS for nuts and dried fruit; TRIPLUS free-fall models for fresh, dried, or frozen products; and MAGNUS for delicate fruit.'],
  ['XAVIS 食品異物 X 光檢測', 'XAVIS Food X-ray Foreign-Object Inspection'],
  ['XAVIS 食品 X 光檢測系列列有小包裝或未包裝、低密度中型包裝或散裝、高密度中型包裝、管道式、大型包裝、小型罐頭或瓶子包裝、大型罐頭或瓶子包裝，以及魚骨或雞骨專用的 X 光食品自動異物檢測機。', 'The XAVIS Food X-ray range includes systems for small or unpackaged products, low-density medium packs or bulk products, high-density medium packs, pipeline products, large packs, small cans or bottles, large cans or bottles, and fish or chicken bone inspection.'],
  ['XAVIS 自動重量與重量分級檢測', 'XAVIS Checkweighing and Weight Grading'],
  ['XAVIS 自動重量檢測機包括 CWF590W 輕量型、CWF590WR 滾輪式、CSCAN 自動重量檢測機及 CWIN69X 多列式重量檢測機。網站亦列有 XAVIS 重量分級檢測機與 MDN-200AD、MDN-200AH 鋁箔金屬檢測機。', 'XAVIS checkweighers include the CWF590W lightweight model, CWF590WR roller model, CSCAN automatic checkweigher, and CWIN69X multi-lane checkweigher. The website also lists XAVIS weight grading systems and the MDN-200AD and MDN-200AH metal detectors for foil packaging.'],
  ['Smart Grader 採樣分析', 'Smart Grader Sampling Analysis'],
  ['Smart Grader 系列包括智慧採樣分析器與智慧分級機。', 'The Smart Grader range includes a smart sampling analyser and smart grader.'],
  ['MEAF 與 PROMIX', 'MEAF and PROMIX'],
  ['MEAF 提供板材押出生產線。PROMIX 物理發泡系列包括 P1 冷卻混合器與熔體混合器。', 'MEAF provides sheet extrusion lines. The PROMIX Physical Foaming range includes the P1 Cooling Mixer and Melt Mixer.'],
  ['SBI 測厚儀', 'SBI Thickness Gauges'],
  ['SBI 測厚儀系列包括 KAPA I 與 KAPA II 電容或渦流雙感測厚薄儀、KAPA IR 紅外線厚薄儀、XRS SOFT X-RAY 低能量 X 光厚薄儀、SHADOW 雷射陰影測量厚薄儀及 STG 雷射位移測量厚薄儀。', 'The SBI Thickness Gauges range includes KAPA I and KAPA II capacitive or eddy-current dual-sensor gauges, the KAPA IR infrared gauge, the XRS SOFT X-RAY low-energy X-ray gauge, the SHADOW laser-shadow gauge, and the STG laser-displacement gauge.'],
  ['NIR 手持式分析儀', 'NIR Handheld Analysers'],
  ['NIR 系列包括手持式 NIR 分析儀（塑料用）、手持式 NIR 分析儀（紡織用）及手持螢幕 NIR 分析儀（塑料用）。', 'The NIR range includes handheld NIR analysers for plastics and textiles, plus a handheld-screen NIR analyser for plastics.'],
  ['NIHOT 回收再生', 'NIHOT Recycling and Recovery'],
  ['NIHOT 回收再生系列包括 SDM 移動式風選機、SDI 風選機、WSF 風選機、DDS 風選機、SDX 風選機及碟篩。網站亦將回收再生列為公司服務領域。', 'The NIHOT Recycling and Recovery range includes the SDM Mobile Air Separator, SDI, WSF, DDS, and SDX Air Separators, plus a Disc Screen. Recycling and Recovery is also listed as a company service area.'],
  ['Matthiessen 與合軒設備', 'Matthiessen and Unirise Equipment'],
  ['Matthiessen 系列列有 SFIIIK3 破袋機。合軒設備列有渦電流分選機、磁滾筒、上吸式磁鐵及鋁罐分選機。', 'The Matthiessen range includes the SFIIIK3 Bag Opener. Unirise equipment includes an Eddy-current Separator, Magnetic Drum, Overband Magnet, and Aluminium-can Sorter.'],
  ['聯絡與詢價', 'Contact and Enquiries'],
  ['可使用網站的詢價系統提出產品詢問與資料索取。合軒科技電話為 06-3319283，Email 為 info-unirise@unirise.tw，地址為台南市東區裕義路598號。', 'Use the website enquiry system for product questions and information requests. Unirise Technology can be reached at 06-3319283 or info-unirise@unirise.tw, at No. 598, Yuyi Road, East District, Tainan City, Taiwan.'],
  ['下載專區提供 NIHOT 回收再生、OPTIMUM 食材分選、PROMIX 塑膠化工及 XAVIS X 光檢測等分類的產品資料索取入口。', 'The Downloads section provides product-information request entry points for NIHOT Recycling and Recovery, OPTIMUM Food Sorting, PROMIX Plastics and Chemicals, and XAVIS X-ray Inspection.'],
];

function english(value: string) {
  // Apply complete sentences and product names before their shorter parts.
  // Otherwise a label such as "回收再生" can be replaced before the matching
  // full English sentence is reached, leaving a mixed-language result.
  return [...phrases].sort(([source], [other]) => other.length - source.length).reduce(
    (translated, [source, target]) => translated.replaceAll(source, target),
    value,
  );
}

function translateValue(value: unknown): unknown {
  if (typeof value === 'string') return english(value);
  if (Array.isArray(value)) return value.map(translateValue);
  if (!value || typeof value !== 'object') return value;
  return Object.fromEntries(
    Object.entries(value).map(([key, entry]) => [key, translateValue(entry)]),
  );
}

/** Translates only reader-facing text; URLs, models, and identifiers stay exact. */
export function englishSeedPayload<T extends TranslationPayload>(payload: T): T {
  return { ...payload, text: translateValue(payload.text) } as T;
}
