import type { TranslationPayload } from './translation-types';

// The initial English copy keeps the public site useful on its first deploy.
// Administrators can replace these drafts in the translation dashboard later.
const phrases: ReadonlyArray<readonly [string, string]> = [
  ['從天然或加工的食品原物料依顏色/外觀\n瑕疵透過自動化分選機完成品質等級分類', 'Automated sorting classifies natural or processed food ingredients by colour and appearance defects.'],
  ['各類食品包裝型態的X光機檢查,為食品出廠前的安全把關', 'X-ray inspection for every food packaging format helps safeguard products before shipment.'],
  ['肉類及無刺鮮魚的高解析度X光機', 'High-resolution X-ray systems for meat and boneless fresh fish.'],
  ['食品容器生產的物理性發泡技術裝置', 'Physical foaming equipment for food-container production.'],
  ['消費端廢棄物整體風選分類設備', 'Complete air-separation and sorting equipment for post-consumer waste.'],
  ['填寫下列表單後，系統會直接將需求送交合軒科技；業務團隊將於一個工作天內回覆。', 'Complete the form to send your requirements directly to Unirise Technology. Our sales team will reply within one business day.'],
  ['請說明您的產線需求、欲檢測／分選的產品與預計導入時間。', 'Please describe your production-line requirements, the products to inspect or sort, and your expected implementation timeline.'],
  ['已收到您的詢問；我們將於一個工作天內以電子郵件與您聯絡。', 'We received your enquiry and will contact you by email within one business day.'],
  ['已收到您的詢問；通知服務暫時延遲，我們仍會儘快與您聯絡。', 'We received your enquiry. Notifications are temporarily delayed, but we will contact you as soon as possible.'],
  ['目前無法送出詢問，請稍後再試，或直接聯絡我們。', 'We cannot send your enquiry right now. Please try again later or contact us directly.'],
  ['「{group}」為合軒科技原網站所列的正式產品與服務分類。', '“{group}” is an official product and service category listed on the Unirise website.'],
  ['完整規格、選配與適用產線請向合軒科技確認。', 'Please contact Unirise Technology to confirm full specifications, options, and suitable production lines.'],
  ['您好，我是合軒科技的測試版網站助理。我可以協助您了解產品領域、代理品牌、聯絡方式與詢價流程。', 'Hello, I am the Unirise website assistant. I can help you explore product areas, represented brands, contact details, and the enquiry process.'],
  ['目前詢問較多，請稍後一分鐘再試。', 'We are receiving many questions. Please try again in one minute.'],
  ['測試版聊天服務正在設定中，請稍後再試或直接聯絡合軒科技。', 'The chat service is still being configured. Please try again later or contact Unirise directly.'],
  ['目前無法取得回覆，請稍後再試或直接使用詢價系統。', 'We cannot retrieve a reply at the moment. Please try again later or use the enquiry form.'],
  ['聊天內容請勿輸入敏感個資。', 'Please do not enter sensitive personal information in the chat.'],
  ['聯絡資料僅用於回覆本次需求。', 'Your contact details are used only to respond to this request.'],
  ['已收到您的需求；目前通知服務暫時無法使用，聯絡可能稍有延遲。', 'We received your request. Notifications are temporarily unavailable, so our reply may be delayed.'],
  ['已收到您的需求，我們會儘快與您聯絡。', 'We received your request and will contact you as soon as possible.'],
  ['資料未能送出，請確認必填欄位後再試。', 'Your information could not be sent. Please check the required fields and try again.'],
  ['送出次數較多，請稍後再試。', 'Too many submissions. Please try again later.'],
  ['雞骨魚骨專用X光異物檢測機 Xavis', 'Xavis X-ray Foreign-Object Inspection System for Fish and Chicken Bones'],
  ['M1 SF 皮帶稱重機和袋裝填充機 Manter', 'Manter M1 SF Belt Weigher and Bag Filling Machine'],
  ['多段式重量分級機 Xavis', 'Xavis Multi-stage Weight Grader'],
  ['番茄自動包裝線 Manter', 'Manter Automated Tomato Packaging Line'],
  ['專為魚刺、魚骨及雞骨等低密度異物設計的 X 光檢測系統。結合高解析 X 光成像與 AI 辨識技術，提升檢測精度與食品安全。', 'An X-ray inspection system designed for low-density foreign objects such as fish bones and chicken bones. High-resolution imaging and AI recognition improve detection accuracy and food safety.'],
  ['專為易受損蔬果打造的自動化包裝系統。結合溫和秤重與自動袋裝填充，兼顧產品品質與包裝效率。', 'An automated packaging system for delicate fruit and vegetables, combining gentle weighing and automatic bag filling to protect product quality and packaging efficiency.'],
  ['專為提升水產加工效率而設計的自動化分級設備。兼顧分級精度、作業效率與產品規格一致性。', 'Automated grading equipment designed to improve seafood-processing efficiency while maintaining grading accuracy, operating efficiency, and consistent product specifications.'],
  ['專為番茄及易受損蔬果打造的自動化包裝系統。兼顧產品品質、包裝效率與產線彈性配置需求。', 'An automated packaging system for tomatoes and delicate fruit and vegetables, balancing product quality, packaging efficiency, and flexible production-line configuration.'],
  ['有哪些食品分選方案？', 'What food-sorting solutions are available?'],
  ['X 光檢測能協助什麼？', 'How can X-ray inspection help?'],
  ['如何聯絡或詢價？', 'How can I contact Unirise or request a quote?'],
  ['食品生產者到消費端的循環自動化方案', 'Circular automation solutions from food production to post-consumer recovery'],
  ['食品生產循環自動化方案', 'Food-production circular automation solutions'],
  ['食材分選', 'Food Sorting'],
  ['X光機異物檢測', 'X-ray Foreign-Object Inspection'],
  ['回收再生', 'Recycling and Recovery'],
  ['塑膠化工', 'Plastics and Chemicals'],
  ['產業服務', 'Industry Services'],
  ['代理品牌', 'Represented Brands'],
  ['最新消息', 'News'],
  ['下載專區', 'Downloads'],
  ['詢價系統', 'Request a Quote'],
  ['聯絡我們', 'Contact Us'],
  ['產品目錄', 'Product Catalog'],
  ['產品詢問與資料索取', 'Product Enquiries and Information Requests'],
  ['加入詢問車', 'Add to Enquiry'],
  ['公司地址', 'Address'],
  ['詢問車', 'Enquiry List'],
  ['語系', 'Language'],
  ['回到首頁', 'Back to Home'],
  ['主要選單', 'Main Navigation'],
  ['開啟選單', 'Open Menu'],
  ['回到頂端', 'Back to Top'],
  ['展開產業服務子選單', 'Expand industry-services submenu'],
  ['展開代理品牌子選單', 'Expand represented-brands submenu'],
  ['展開下載專區子選單', 'Expand downloads submenu'],
  ['台南市東區裕義路598號', 'No. 598, Yuyi Road, East District, Tainan City, Taiwan'],
  ['合軒科技有限公司', 'Unirise Technology Inc.'],
  ['我們提供', 'We provide'],
  ['品牌介紹', 'Brand Overview'],
  ['自動重量檢測機', 'Automatic Checkweighers'],
  ['重量分級檢測機', 'Weight Grading Systems'],
  ['食品異物X光機檢測', 'Food X-ray Foreign-Object Inspection'],
  ['鋁箔金屬檢測機', 'Metal Detection for Foil Packaging'],
  ['工業產品X光機檢測', 'Industrial-product X-ray Inspection'],
  ['採樣分析', 'Sampling Analysis'],
  ['板材押出生產線', 'Sheet Extrusion Lines'],
  ['物理發泡', 'Physical Foaming'],
  ['測厚儀', 'Thickness Gauges'],
  ['手持式分析儀', 'Handheld Analysers'],
  ['破袋機', 'Bag Openers'],
  ['渦電流分選機', 'Eddy-current Separators'],
  ['磁滾筒', 'Magnetic Drums'],
  ['上吸式磁鐵', 'Overband Magnets'],
  ['鋁罐分選機', 'Aluminium-can Sorters'],
  ['聯絡方式與詢價流程', 'contact details and the enquiry process'],
  ['公司名稱', 'Company'],
  ['聯絡電話', 'Phone'],
  ['電子信箱', 'Email'],
  ['詢問產品', 'Product of Interest'],
  ['需求說明', 'Requirements'],
  ['送出詢問', 'Send Enquiry'],
  ['送出中…', 'Sending…'],
  ['服務電話', 'Service Phone'],
  ['產品資料索取', 'Request Product Information'],
  ['請填寫此欄位。', 'Please complete this field.'],
  ['請輸入有效的電子郵件地址。', 'Please enter a valid email address.'],
  ['聯絡專員', 'Talk to a Specialist'],
  ['索取報價', 'Request a Quote'],
  ['開啟聊天', 'Open Chat'],
  ['關閉聊天', 'Close Chat'],
  ['送出問題', 'Send Question'],
  ['請輸入您的問題', 'Enter your question'],
  ['正在回覆', 'Replying'],
  ['參考網站內容：', 'Website sources:'],
  ['累計訪客', 'Total visitors'],
  ['今日訪客', 'Visitors today'],
  ['訪客統計載入中', 'Loading visitor statistics'],
  ['上一組品牌', 'Previous brands'],
  ['下一組品牌', 'Next brands'],
  ['主視覺輪播', 'Main visual carousel'],
  ['向下捲動', 'Scroll down'],
  ['了解更多', 'Learn more'],
];

function english(value: string) {
  return phrases.reduce(
    (translated, [source, target]) => translated.replaceAll(source, target),
    value,
  );
}

function translateValue(value: unknown): unknown {
  if (typeof value === 'string') return english(value);
  if (Array.isArray(value)) return value.map(translateValue);
  if (!value || typeof value !== 'object') return value;
  return Object.fromEntries(
    Object.entries(value).map(([key, entry]) => [key, translateValue(entry)]),
  );
}

/** Translates only reader-facing text; URLs, models, and identifiers stay exact. */
export function englishSeedPayload<T extends TranslationPayload>(payload: T): T {
  return { ...payload, text: translateValue(payload.text) } as T;
}
