// Canonical Chinese copy extracted from the original public pages. Stable IDs and
// assets are kept separate from reader-facing prose for translation validation.
const tuples = (rows: string[][]) => rows.map(([label, id]) => ({ label, id }));
const industryGroups = [
  {
    title: '食材分選',
    id: '1',
    items: tuples([
      ['OPTIMUM-食材分選', '73'],
      ['Smart Grader-採樣分析', '82'],
    ]),
  },
  {
    title: 'X光機異物檢測',
    id: '4',
    items: tuples([
      ['XAVIS-X光機檢測', '77'],
      ['XAVIS-FSCAN自動重量檢測機', '97'],
      ['XAVIS-FSCAN重量分級檢測機', '100'],
      ['XAVIS-FSCAN鋁箔金屬檢測機', '98'],
    ]),
  },
  {
    title: '回收再生',
    id: '6',
    items: tuples([
      ['NIR手持式分析儀', '84'],
      ['NIHOT-回收再生', '78'],
      ['Matthiessen-破袋機', '91'],
      ['合軒', '81'],
    ]),
  },
  {
    title: '塑膠化工',
    id: '7',
    items: tuples([
      ['MEAF-板材押出生產線', '86'],
      ['PROMIX-物理發泡', '79'],
      ['SBI-測厚儀', '96'],
    ]),
  },
];

const brandGroups = [
  {
    title: '品牌介紹',
    id: '89',
    items: tuples([
      ['OPTIMUM', '90'],
      ['XAVIS', '91'],
      ['Smart Grader', '110'],
      ['MEAF', '124'],
      ['PROMIX', '93'],
      ['SBI', '146'],
      ['NIR', '109'],
      ['NIHOT', '92'],
      ['Matthiessen', '131'],
      ['合軒', '98'],
    ]),
  },
  {
    title: 'OPTIMUM-食材分選',
    id: '1',
    items: tuples([
      ['NOVUS (皮帶式-適用新鮮、乾燥或冷凍產品)', '78'],
      ['VENTUS (適用堅果和乾果等產品)', '80'],
      ['TRIPLUS (自由落體式-適用新鮮、乾燥或冷凍產品)', '79'],
      ['MAGNUS (適用易碎水果)', '150'],
    ]),
  },
  {
    title: 'XAVIS-自動重量檢測機',
    id: '147',
    items: tuples([
      ['CWF590W輕量型重量檢測機', '156'],
      ['CWF590WR滾輪式重量檢測機', '158'],
      ['CSCAN自動重量檢測機', '149'],
      ['CWIN69X多列式重量檢測機', '161'],
    ]),
  },
  {
    title: 'XAVIS-重量分級檢測機',
    id: '159',
    items: tuples([['XAVIS重量分級檢測機', '160']]),
  },
  {
    title: 'XAVIS-食品異物X光機檢測',
    id: '2',
    items: tuples([
      ['小包裝/未包裝X光食品自動異物檢測機', '5'],
      ['低密度中型包裝/散裝 X光食品自動異物檢測機', '81'],
      ['高密度中型包裝 X光食品自動異物檢測機', '82'],
      ['管道式 X光食品自動異物檢測機', '83'],
      ['大型包裝 X光食品自動異物檢測機', '84'],
      ['小型罐頭/瓶子包裝 X光食品自動異物檢測機', '85'],
      ['大型罐頭/瓶子包裝 X光食品自動異物檢測機', '86'],
      ['魚骨/雞骨專用 X光食品自動異物檢測機', '127'],
    ]),
  },
  {
    title: 'XAVIS-鋁箔金屬檢測機',
    id: '152',
    items: tuples([
      ['MDN-200AD鋁箔金屬檢測機(標準)', '153'],
      ['MDN-200AH鋁箔金屬檢測機(進階)', '154'],
    ]),
  },
  {
    title: 'XAVIS-工業產品X光機檢測',
    id: '120',
    items: tuples([['電池檢測專用', '121']]),
  },
  {
    title: 'Smart Grader-採樣分析',
    id: '111',
    items: tuples([
      ['智慧採樣分析器', '113'],
      ['智慧分級機', '114'],
    ]),
  },
  {
    title: 'MEAF-板材押出生產線',
    id: '122',
    items: tuples([['板材押出生產線', '123']]),
  },
  {
    title: 'PROMIX-物理發泡',
    id: '72',
    items: tuples([
      ['P1 冷卻混合器', '128'],
      ['熔體混合器', '129'],
    ]),
  },
  {
    title: 'SBI-測厚儀',
    id: '140',
    items: tuples([
      ['KAPA I & KAPA II 電容/渦流雙感測厚薄儀', '141'],
      ['KAPA IR 紅外線厚薄儀', '142'],
      ['XRS SOFT X-RAY 低能量X光厚薄儀', '143'],
      ['SHADOW 雷射陰影測量厚薄儀', '144'],
      ['STG 雷射位移測量厚薄儀', '145'],
    ]),
  },
  {
    title: 'NIR手持式分析儀',
    id: '112',
    items: tuples([
      ['手持式NIR分析儀-塑料用', '116'],
      ['手持式NIR分析儀-紡織用', '151'],
      ['手持螢幕NIR分析儀-塑料用', '155'],
    ]),
  },
  {
    title: 'NIHOT-回收再生',
    id: '7',
    items: tuples([
      ['SDM 移動式風選機', '87'],
      ['SDI 風選機', '104'],
      ['WSF 風選機', '105'],
      ['DDS 風選機', '106'],
      ['SDX 風選機', '107'],
      ['碟篩', '108'],
    ]),
  },
  {
    title: 'Matthiessen-破袋機',
    id: '137',
    items: tuples([['SFIIIK3 破袋機', '138']]),
  },
  {
    title: '合軒',
    id: '99',
    items: tuples([
      ['渦電流分選機', '100'],
      ['磁滾筒', '101'],
      ['上吸式磁鐵', '102'],
      ['鋁罐分選機', '103'],
    ]),
  },
];

const groupNotes: Record<string, string> = {
  食材分選: '原網站將天然或加工食品原物料依顏色與外觀瑕疵進行自動化品質分級。',
  X光機異物檢測:
    '原網站提供各類食品包裝型態的 X 光檢查，作為食品出廠前的安全把關。',
  回收再生: '原網站列出消費端廢棄物的整體風選分類設備與回收再生解決方案。',
  塑膠化工: '原網站涵蓋食品容器物理性發泡、板材押出與厚薄量測相關技術。',
  'OPTIMUM-食材分選':
    'OPTIMUM 食材分選系列包含皮帶式、自由落體式及適用堅果、乾果與易碎水果的機型。',
  'XAVIS-食品異物X光機檢測':
    'XAVIS 食品 X 光檢測系列包含未包裝、袋裝、罐裝、瓶裝、管道式與魚骨／雞骨等應用。',
  'NIHOT-回收再生': 'NIHOT 系列包含移動式與固定式風選機、碟篩等回收再生設備。',
};

const industryTitles: Record<string, string> = {
  '1': '食材分選',
  '4': 'X光機異物檢測',
  '6': '回收再生',
  '7': '塑膠化工',
  '73': 'OPTIMUM-食材分選',
  '82': 'Smart Grader-採樣分析',
  '77': 'XAVIS-X光機檢測',
  '97': 'XAVIS-FSCAN自動重量檢測機',
  '100': 'XAVIS-FSCAN重量分級檢測機',
  '98': 'XAVIS-FSCAN鋁箔金屬檢測機',
  '84': 'NIR手持式分析儀',
  '78': 'NIHOT-回收再生',
  '91': 'Matthiessen-破袋機',
  '81': '合軒',
  '86': 'MEAF-板材押出生產線',
  '79': 'PROMIX-物理發泡',
  '96': 'SBI-測厚儀',
};

const brandTitles: Record<string, string> = {
  '89': '品牌介紹',
  '90': 'OPTIMUM',
  '91': 'XAVIS',
  '110': 'Smart Grader',
  '124': 'MEAF',
  '93': 'PROMIX',
  '146': 'SBI',
  '109': 'NIR',
  '92': 'NIHOT',
  '131': 'Matthiessen',
  '98': '合軒',
  '1': 'OPTIMUM-食材分選',
  '78': 'NOVUS (皮帶式-適用新鮮、乾燥或冷凍產品)',
  '80': 'VENTUS (適用堅果和乾果等產品)',
  '79': 'TRIPLUS (自由落體式-適用新鮮、乾燥或冷凍產品)',
  '150': 'MAGNUS (適用易碎水果)',
  '147': 'XAVIS-自動重量檢測機',
  '156': 'CWF590W輕量型重量檢測機',
  '158': 'CWF590WR滾輪式重量檢測機',
  '149': 'CSCAN自動重量檢測機',
  '161': 'CWIN69X多列式重量檢測機',
  '159': 'XAVIS-重量分級檢測機',
  '160': 'XAVIS重量分級檢測機',
  '2': 'XAVIS-食品異物X光機檢測',
  '5': '小包裝/未包裝X光食品自動異物檢測機',
  '81': '低密度中型包裝/散裝 X光食品自動異物檢測機',
  '82': '高密度中型包裝 X光食品自動異物檢測機',
  '83': '管道式 X光食品自動異物檢測機',
  '84': '大型包裝 X光食品自動異物檢測機',
  '85': '小型罐頭/瓶子包裝 X光食品自動異物檢測機',
  '86': '大型罐頭/瓶子包裝 X光食品自動異物檢測機',
  '127': '魚骨/雞骨專用 X光食品自動異物檢測機',
  '152': 'XAVIS-鋁箔金屬檢測機',
  '153': 'MDN-200AD鋁箔金屬檢測機(標準)',
  '154': 'MDN-200AH鋁箔金屬檢測機(進階)',
  '120': 'XAVIS-工業產品X光機檢測',
  '121': '電池檢測專用',
  '111': 'Smart Grader-採樣分析',
  '113': '智慧採樣分析器',
  '114': '智慧分級機',
  '122': 'MEAF-板材押出生產線',
  '123': '板材押出生產線',
  '72': 'PROMIX-物理發泡',
  '128': 'P1 冷卻混合器',
  '129': '熔體混合器',
  '140': 'SBI-測厚儀',
  '141': 'KAPA I & KAPA II 電容/渦流雙感測厚薄儀',
  '142': 'KAPA IR 紅外線厚薄儀',
  '143': 'XRS SOFT X-RAY 低能量X光厚薄儀',
  '144': 'SHADOW 雷射陰影測量厚薄儀',
  '145': 'STG 雷射位移測量厚薄儀',
  '112': 'NIR手持式分析儀',
  '116': '手持式NIR分析儀-塑料用',
  '151': '手持式NIR分析儀-紡織用',
  '155': '手持螢幕NIR分析儀-塑料用',
  '7': 'NIHOT-回收再生',
  '87': 'SDM 移動式風選機',
  '104': 'SDI 風選機',
  '105': 'WSF 風選機',
  '106': 'DDS 風選機',
  '107': 'SDX 風選機',
  '108': '碟篩',
  '137': 'Matthiessen-破袋機',
  '138': 'SFIIIK3 破袋機',
  '99': '合軒',
  '100': '渦電流分選機',
  '101': '磁滾筒',
  '102': '上吸式磁鐵',
  '103': '鋁罐分選機',
};

export const initialPublicContent = {
  home: {
    kind: 'home' as const,
    text: {
      heading: '我們提供',
      eyebrow: '解決方案總覽',
      introduction: '食品生產者到消費端的循環自動化方案',
      services: [
        '從天然或加工的食品原物料依顏色/外觀\n瑕疵透過自動化分選機完成品質等級分類',
        '各類食品包裝型態的X光機檢查,為食品出廠前的安全把關',
        '肉類及無刺鮮魚的高解析度X光機',
        '食品容器生產的物理性發泡技術裝置',
        '消費端廢棄物整體風選分類設備',
      ],
      featureLabels: ['食材分選', 'X光檢測', '回收再生', '塑膠化工'],
      agencyLabels: [
        '板材押出生產線',
        '風選機',
        '食材分選',
        '物理發泡',
        '測厚儀',
        '採樣分析',
        'NIR手持式分析儀',
        'X光食品異物檢測',
        '渦電流及除鐵設備',
      ],
      aboutImage: '食品生產循環自動化方案',
      hero: '主視覺輪播',
      previousSlide: '上一張主視覺',
      nextSlide: '下一張主視覺',
      scrollDown: '向下捲動',
      industry: '產業服務',
      brands: '代理品牌',
      brandEyebrow: '代理品牌',
      previousBrands: '上一組品牌',
      nextBrands: '下一組品牌',
      news: '最新消息',
      newsEyebrow: '最新消息',
      more: '了解更多',
      readMore: '了解更多',
    },
    literals: {
      featureIds: ['1', '4', '6', '7'],
      featureImages: [
        '/reference/original/feature01.jpg',
        '/reference/original/feature02.jpg',
        '/reference/original/feature03.jpg',
        '/reference/original/feature04.jpg',
      ],
      agencyIds: ['122', '7', '1', '72', '140', '111', '112', '2', '99'],
      agencyImages: [
        'index_005.jpg',
        'index_003.jpg',
        'index_004.jpg',
        'index_001.jpg',
        'index_010.png',
        'index_006.jpg',
        'index_007.jpg',
        'index_008.jpg',
        'index_009.jpg',
      ].map((name) => '/reference/original/' + name),
      newsIds: ['3944', '3943', '3942', '3941'],
    },
  },
  catalog: {
    kind: 'catalog' as const,
    text: {
      title: '產品目錄',
      industry: '產業服務',
      brand: '代理品牌',
      industryEyebrow: '產業服務',
      brandEyebrow: '代理品牌',
      industryTitles,
      brandTitles,
      groupNotes,
      specialProduct: '3. 魚骨/雞骨檢測 FSCAN-4350G X光食品自動異物檢測機',
      defaultNote: '「{group}」為合軒科技原網站所列的正式產品與服務分類。',
      specifications: '完整規格、選配與適用產線請向合軒科技確認。',
      inquire: '加入詢問車',
    },
    literals: { specialProductId: '127', model: 'FSCAN-4350G' },
  },
  contact: {
    kind: 'contact' as const,
    text: {
      title: '聯絡我們',
      eyebrow: '聯絡',
      company: '合軒科技有限公司',
      phone: '電話',
      email: '信箱',
      address: '地址',
      addressValue: '台南市東區裕義路598號',
      action: '立即聯絡',
    },
    literals: {
      phoneUrl: 'tel:063319283',
      phone: '06-3319283',
      emailUrl: 'mailto:info-unirise@unirise.tw',
      email: 'info-unirise@unirise.tw',
    },
  },
  inquiry: {
    kind: 'inquiry' as const,
    text: {
      title: '詢價系統',
      eyebrow: '詢價',
      heading: '產品詢問與資料索取',
      help: '填寫下列表單後，系統會直接將需求送交合軒科技；業務團隊將於一個工作天內回覆。',
      name: '姓名',
      company: '公司名稱',
      phone: '聯絡電話',
      email: '電子信箱',
      product: '詢問產品',
      message: '需求說明',
      placeholder: '請說明您的產線需求、欲檢測／分選的產品與預計導入時間。',
      submit: '送出詢問',
      sending: '送出中…',
      sent: '已收到您的詢問；我們將於一個工作天內以電子郵件與您聯絡。',
      delayed: '已收到您的詢問；通知服務暫時延遲，我們仍會儘快與您聯絡。',
      error: '目前無法送出詢問，請稍後再試，或直接聯絡我們。',
      rateLimited: '送出次數較多，請稍後再試。',
      servicePhone: '服務電話',
      subject: '詢問產品：',
      defaultSubject: '產品資料索取',
      emailName: '姓名：',
      emailCompany: '公司：',
      emailPhone: '電話：',
      emailEmail: 'Email：',
      emailMessage: '需求說明：',
      required: '請填寫此欄位。',
      invalidEmail: '請輸入有效的電子郵件地址。',
    },
    literals: {
      emailUrl: 'mailto:info-unirise@unirise.tw',
      email: 'info-unirise@unirise.tw',
      phone: '06-3319283',
    },
  },
  chrome: {
    kind: 'chrome' as const,
    text: {
      company: '合軒科技有限公司',
      home: '首頁',
      address: '公司地址',
      contact: '聯絡我們',
      search: '搜尋',
      cart: '詢問車',
      language: '語系',
      selectLanguage: '選擇語言⌄',
      homeLink: '回到首頁',
      menu: '主要選單',
      openMenu: '開啟選單',
      top: '回到頂端',
      nav: [
        '產業服務',
        '代理品牌',
        '最新消息',
        '下載專區',
        '詢價系統',
        '聯絡我們',
      ],
      expandIndustry: '展開產業服務子選單',
      expandBrand: '展開代理品牌子選單',
      expandDownloads: '展開下載專區子選單',
      industryMenu: industryGroups.map((group) => ({
        title: group.title,
        items: group.items.map((item) => item.label),
      })),
      brandMenu: brandGroups.map((group) => ({
        title: group.title,
        items: group.items.map((item) => item.label),
      })),
      downloads: [
        'NIHOT-回收再生',
        'OPTIMUM-食材分選',
        'PROMIX-塑膠化工',
        'XAVIS-X光檢測',
      ],
      footerAddress: '台南市東區裕義路598號',
      copyright: 'Copyright © 2021 合軒科技有限公司 All Rights Reserved.',
      visitorsLoading: '訪客統計載入中',
      visitorsTotal: '累計訪客',
      visitorsToday: '今日訪客',
      chat: {
        title: '合軒科技網站助理',
        subtitle: '測試版｜公開資訊問答',
        welcome:
          '您好，我是合軒科技的測試版網站助理。我可以協助您了解產品領域、代理品牌、聯絡方式與詢價流程。',
        suggestions: [
          '有哪些食品分選方案？',
          'X 光檢測能協助什麼？',
          '如何聯絡或詢價？',
        ],
        rateLimited: '目前詢問較多，請稍後一分鐘再試。',
        notConfigured:
          '測試版聊天服務正在設定中，請稍後再試或直接聯絡合軒科技。',
        error: '目前無法取得回覆，請稍後再試或直接使用詢價系統。',
        open: '開啟聊天',
        close: '關閉聊天',
        sources: '參考網站內容：',
        replying: '正在回覆',
        followUp: '後續服務',
        quote: '索取報價',
        specialist: '聯絡專員',
        quoteForm: '索取報價表單',
        specialistForm: '聯絡專員表單',
        closeLead: '關閉聯絡表單',
        name: '姓名',
        email: '電子信箱',
        company: '公司',
        phone: '電話',
        topic: '產品／主題',
        message: '需求說明',
        contactPrivacy: '聯絡資料僅用於回覆本次需求。',
        sending: '送出中…',
        submitLead: '送出需求',
        leadRateLimited: '送出次數較多，請稍後再試。',
        leadInvalid: '資料未能送出，請確認必填欄位後再試。',
        leadDelayed:
          '已收到您的需求；目前通知服務暫時無法使用，聯絡可能稍有延遲。',
        leadReceived: '已收到您的需求，我們會儘快與您聯絡。',
        leadError: '資料未能送出，請稍後再試。',
        privacy: '聊天內容請勿輸入敏感個資。',
        placeholder: '請輸入您的問題',
        question: '聊天問題',
        send: '送出問題',
      },
    },
    literals: {
      navUrls: [
        '/catalog?type=industry&id=73',
        '/catalog?type=brand&id=89',
        '/news',
        '/downloads?id=3853',
        '/inquiry',
        '/contact',
      ],
      industryMenu: industryGroups.map((group) => ({
        id: group.id,
        items: group.items.map((item) => item.id),
      })),
      brandMenu: brandGroups.map((group) => ({
        id: group.id,
        items: group.items.map((item) => item.id),
      })),
      downloadIds: ['3853', '77', '3854', '78'],
      addressUrl: 'https://goo.gl/maps/dvcWWbp4xf8AZ3dF6',
      footerAddressUrl: 'https://goo.gl/maps/oqLuxoMzVYdmJEwg9',
      phoneUrl: 'tel:06-3319283',
      phone: '06-3319283',
      emailUrl: 'mailto:info-unirise@unirise.tw',
      email: 'info-unirise@unirise.tw',
      logoUrl: '/reference/original/logo.png',
      footerLogoUrl: '/reference/original/logo_footer.svg',
      facebookUrl:
        'https://www.facebook.com/%E5%90%88%E8%BB%92%E7%A7%91%E6%8A%80%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8-161123071369104',
      lineUrl: 'https://line.me/ti/p/W1QdEgfzdb',
      youtubeUrl: 'https://www.youtube.com/channel/UCuIR83-YHMNnVc8lbaDB2nQ',
    },
  },
};

export type PublicContentId = keyof typeof initialPublicContent;
export const PUBLIC_CONTENT_IDS = Object.keys(
  initialPublicContent,
) as PublicContentId[];
